- hosts: 127.0.0.1 
  connection: local
  sudo: true
  vars:
      username: "{{ lookup('env', 'USER') }}"
  tasks:
    - name: add php-7.0 repository 
      apt_repository: repo='ppa:ondrej/php-7.0'

    - name: apt update
      apt: update_cache=yes

    - name: install apache2 
      apt: name=apache2

    - name: enable rewrite
      command: a2enmod rewrite 

    - name: apt install php7.0
      apt: name={{ item }} 
      with_items:
        - php7.0
        - php7.0-mysql
        - php7.0-curl

    - name: apt install git 
      apt: name=git

    - name: is composer already installed
      shell: /usr/bin/test -f /usr/bin/composer 
      register: check_composer
      ignore_errors: True

    - name: install composer
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin
      when: check_composer|failed

    - name: move composer.phar to composer
      file: src=/usr/bin/composer.phar dest=/usr/bin/composer state=link
      when: check_composer|failed

    - name: copy apache2 default_config 
      template: src=templates/000-default.conf dest=/etc/apache2/sites-available/000-default.conf mode=0644

    - name: ensure apache start
      service: name=apache2 state=restarted enabled=yes

    - name: change timezone to JST
      command: echo "Asia/Tokyo" | sudo tee /etc/timezone

    - name: change timezone reconfigure
      command: dpkg-reconfigure --frontend noninteractive tzdata

    - name: install mysql-server
      apt: name={{ item }}
      with_items:
        - mysql-server
        - python-mysqldb

    - name: start and enable mysql
      service: name=mysql state=started enabled=yes
      sudo: yes
    
    - name: create application database
      mysql_db: name=bench encoding=utf8 state=present
    
    - name: create application database user
      mysql_user: name=bench password=bench host=localhost priv=bench.*:ALL state=present

    - name: clone benchapp
      git: repo=https://github.com/hanhan1978/benchapp.git
           dest=/vagrant/benchapp version=master accept_hostkey=yes

    - name: composer install
      composer: command=install working_dir=/vagrant/benchapp

    - name: link env
      file: src=/vagrant/benchapp/.env.example dest=/vagrant/benchapp/.env state=link

    - name: migration
      shell: >
        cd /vagrant/benchapp;
        php artisan migrate --force;

    - name: seed 
      shell: >
        cd /vagrant/benchapp;
        php artisan db:seed --force;
